// Default agent profile templates for Small World

export const AGENT_TEMPLATES = {
    manager: {
        label: 'Manager',
        name: '',
        profession: 'Management',
        job_title: 'Engineering Manager',
        organization: '',
        personality_traits: {
            openness: 0.6,
            conscientiousness: 0.8,
            extraversion: 0.65,
            agreeableness: 0.65,
            neuroticism: 0.35,
            risk_tolerance: 0.5,
            decision_style: 'analytical',
            motivation_drivers: ['team success', 'career growth', 'impact'],
            core_beliefs: 'People are the most important asset. Process enables scale.',
            biases: ['anchoring bias', 'status quo bias'],
        },
        behavioral_attributes: {
            communication_style: 'direct',
            influence_level: 0.75,
            adaptability: 0.65,
            loyalty: 0.7,
            stress_response: 'Seeks clarity and delegates under pressure',
        },
        contextual_state: {
            current_goals: ['deliver project on time', 'grow team members', 'hit OKRs'],
            current_frustrations: ['unclear requirements', 'cross-team dependencies'],
            incentives: ['team recognition', 'promotion track'],
            constraints: ['headcount budget', 'timeline'],
        },
        external_factors: {
            work_environment: 'Hybrid office/remote tech company',
        },
    },

    ic: {
        label: 'Individual Contributor (IC)',
        name: '',
        profession: 'Engineering',
        job_title: 'Senior Software Engineer',
        organization: '',
        personality_traits: {
            openness: 0.75,
            conscientiousness: 0.7,
            extraversion: 0.45,
            agreeableness: 0.6,
            neuroticism: 0.4,
            risk_tolerance: 0.55,
            decision_style: 'analytical',
            motivation_drivers: ['mastery', 'interesting problems', 'autonomy'],
            core_beliefs: 'Good engineering makes systems reliable and maintainable.',
            biases: ['perfectionism', 'not-invented-here'],
        },
        behavioral_attributes: {
            communication_style: 'direct',
            influence_level: 0.5,
            adaptability: 0.7,
            loyalty: 0.6,
            stress_response: 'Goes deep on problem solving, can become siloed',
        },
        contextual_state: {
            current_goals: ['ship clean code', 'learn new technology', 'reduce tech debt'],
            current_frustrations: ['context switching', 'unclear specs', 'too many meetings'],
            incentives: ['interesting work', 'technical growth', 'compensation'],
            constraints: ['time', 'unclear requirements'],
        },
        external_factors: {
            work_environment: 'Remote-first software team',
        },
    },

    customer: {
        label: 'Customer Persona',
        name: '',
        profession: 'Business',
        job_title: 'Operations Director',
        organization: '',
        personality_traits: {
            openness: 0.55,
            conscientiousness: 0.7,
            extraversion: 0.6,
            agreeableness: 0.65,
            neuroticism: 0.45,
            risk_tolerance: 0.4,
            decision_style: 'analytical',
            motivation_drivers: ['ROI', 'efficiency', 'risk reduction'],
            core_beliefs: 'Investment must deliver measurable business value.',
            biases: ['loss aversion', 'social proof'],
        },
        behavioral_attributes: {
            communication_style: 'direct',
            influence_level: 0.6,
            adaptability: 0.55,
            loyalty: 0.5,
            stress_response: 'Escalates to leadership if value is not clear',
        },
        contextual_state: {
            current_goals: ['reduce operational costs', 'improve team productivity', 'justify tech spend'],
            current_frustrations: ['vendor overpromising', 'integration complexity', 'change management'],
            incentives: ['proven ROI', 'ease of adoption', 'vendor support'],
            constraints: ['budget approval cycles', 'IT gatekeeping'],
        },
        external_factors: {
            work_environment: 'Mid-size enterprise, traditional industry',
            market_exposure: 'Evaluating multiple competing solutions',
        },
    },

    executive: {
        label: 'Executive',
        name: '',
        profession: 'Executive Leadership',
        job_title: 'Chief Product Officer',
        organization: '',
        personality_traits: {
            openness: 0.65,
            conscientiousness: 0.75,
            extraversion: 0.75,
            agreeableness: 0.55,
            neuroticism: 0.3,
            risk_tolerance: 0.65,
            decision_style: 'analytical',
            motivation_drivers: ['company growth', 'market leadership', 'shareholder value'],
            core_beliefs: 'Strategy without execution is hallucination.',
            biases: ['overconfidence bias', 'optimism bias'],
        },
        behavioral_attributes: {
            communication_style: 'direct',
            influence_level: 0.9,
            adaptability: 0.7,
            loyalty: 0.65,
            stress_response: 'Focuses on priorities, delegates details',
        },
        contextual_state: {
            current_goals: ['grow revenue 30% YoY', 'expand market share', 'build leadership team'],
            current_frustrations: ['execution gaps', 'talent retention', 'competitive pressure'],
            incentives: ['equity', 'board confidence', 'industry recognition'],
            constraints: ['board timelines', 'investor expectations', 'cash runway'],
        },
        external_factors: {
            work_environment: 'Growth stage tech company, high pressure environment',
            market_exposure: 'Direct market and competitive exposure',
        },
    },
};
