"""
Metrics router — Question-Based Metrics System

All endpoints serve data from questions_metrics.json generated by
core.question_metrics.QuestionMetrics.  The old hardcoded metrics system
(metrics.json / MetricsReport) has been replaced.
"""

import os
import json
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from sqlalchemy.orm import Session
from .. import crud, models, schemas
from ..database import get_db
from ..deps import get_current_user


router = APIRouter(
    prefix="/api/metrics",
    tags=["metrics"],
)

_RESULT_FILENAME = "questions_metrics.json"


# ── Helpers ────────────────────────────────────────────────────────────────────

def _result_path(outputs_path: str) -> str:
    return os.path.join(outputs_path, _RESULT_FILENAME)


def _read_result(outputs_path: str) -> dict:
    path = _result_path(outputs_path)
    if not os.path.exists(path):
        raise HTTPException(status_code=404, detail="Metrics not generated yet")
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read metrics: {e}")


def _status_from_result(outputs_path: str) -> schemas.MetricsStatusResponse:
    path = _result_path(outputs_path)
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            return schemas.MetricsStatusResponse(
                available=data.get("available", True),
                generated_at=data.get("generated_at"),
                num_rounds=None,
            )
        except Exception:
            return schemas.MetricsStatusResponse(available=True)
    return schemas.MetricsStatusResponse(available=False)


def _run_question_metrics_bg(outputs_path: str, user_id: int | None = None) -> None:
    from core.question_metrics import QuestionMetrics
    qm = QuestionMetrics(outputs_path)
    qm.run()
    if user_id and (qm._usage.input_tokens > 0 or qm._usage.output_tokens > 0):
        from ..database import SessionLocal
        from ..billing import deduct_credits
        db = SessionLocal()
        try:
            deduct_credits(db, user_id, qm._usage, description="Metrics generation")
        except Exception as billing_exc:
            print(f"[billing] deduct_credits failed: {billing_exc}")
        finally:
            db.close()


# ── Session endpoints ───────────────────────────────────────────────────────────

@router.get("/{session_uuid}/status", response_model=schemas.MetricsStatusResponse)
def get_metrics_status(
    session_uuid: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    db_session = crud.get_session(db, session_uuid)
    if not db_session or db_session.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Session not found")
    return _status_from_result(db_session.outputs_path)


@router.post("/{session_uuid}/generate")
def generate_metrics(
    session_uuid: str,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    db_session = crud.get_session(db, session_uuid)
    if not db_session or db_session.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Session not found")
    if db_session.status != "completed":
        raise HTTPException(status_code=400, detail="Simulation must be completed before generating metrics")
    background_tasks.add_task(_run_question_metrics_bg, db_session.outputs_path, current_user.id)
    return {"message": "Metrics generation started"}


@router.get("/{session_uuid}", response_model=schemas.QAMetricsFullResponse)
def get_all_metrics(
    session_uuid: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Return the complete question-based metrics payload for a session."""
    db_session = crud.get_session(db, session_uuid)
    if not db_session or db_session.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Session not found")

    path = _result_path(db_session.outputs_path)
    if not os.path.exists(path):
        return schemas.QAMetricsFullResponse(available=False)

    data = _read_result(db_session.outputs_path)
    return schemas.QAMetricsFullResponse(
        available=data.get("available", True),
        generated_at=data.get("generated_at"),
        objective=data.get("objective", ""),
        questions=data.get("questions", []),
        answers=data.get("answers", []),
        aggregate=data.get("aggregate", {}),
        error=data.get("error"),
    )


# ── Scenario endpoints ─────────────────────────────────────────────────────────

@router.get("/scenario/{scenario_uuid}/status", response_model=schemas.MetricsStatusResponse)
def get_scenario_metrics_status(
    scenario_uuid: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    scenario = crud.get_scenario_by_uuid(db, scenario_uuid)
    if not scenario:
        raise HTTPException(status_code=404, detail="Scenario not found")
    if not scenario.outputs_path:
        return schemas.MetricsStatusResponse(available=False)
    return _status_from_result(scenario.outputs_path)


@router.post("/scenario/{scenario_uuid}/generate")
def generate_scenario_metrics(
    scenario_uuid: str,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    scenario = crud.get_scenario_by_uuid(db, scenario_uuid)
    if not scenario or not scenario.outputs_path:
        raise HTTPException(status_code=404, detail="Scenario not found")
    background_tasks.add_task(_run_question_metrics_bg, scenario.outputs_path, current_user.id)
    return {"message": "Metrics generation started"}


@router.get("/scenario/{scenario_uuid}", response_model=schemas.QAMetricsFullResponse)
def get_all_scenario_metrics(
    scenario_uuid: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Return the complete question-based metrics payload for a scenario."""
    scenario = crud.get_scenario_by_uuid(db, scenario_uuid)
    if not scenario:
        raise HTTPException(status_code=404, detail="Scenario not found")
    if not scenario.outputs_path:
        return schemas.QAMetricsFullResponse(available=False)

    path = _result_path(scenario.outputs_path)
    if not os.path.exists(path):
        return schemas.QAMetricsFullResponse(available=False)

    data = _read_result(scenario.outputs_path)
    return schemas.QAMetricsFullResponse(
        available=data.get("available", True),
        generated_at=data.get("generated_at"),
        objective=data.get("objective", ""),
        questions=data.get("questions", []),
        answers=data.get("answers", []),
        aggregate=data.get("aggregate", {}),
        error=data.get("error"),
    )

